version: 0.1.0-{build}
configuration:
  - Debug
  - Release
before_build:
  - nuget restore
artifacts:
  - path: App.UI.Droid\bin\**\App.UI.Droid-Signed.apk
    name: Android
after_build: 
 - msbuild /t:SignAndroidPackage App.UI.Droid\App.UI.Droid.csproj